name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get your code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Deploy to VM using SSH
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Create app directory
            mkdir -p /home/azureuser/app
            
            # Copy code (exclude unnecessary files)
            rsync -av --delete \
              --exclude='.git/' \
              --exclude='node_modules/' \
              ./ /home/azureuser/app/
            
            # Navigate to app directory
            cd /home/azureuser/app
            
            # Install production dependencies
            npm ci --production
            
            # Create systemd service file
            sudo bash -c 'cat > /etc/systemd/system/hello-api.service <<EOF
            [Unit]
            Description=Hello API Service
            After=network.target

            [Service]
            User=azureuser
            WorkingDirectory=/home/azureuser/app
            ExecStart=/usr/bin/node index.js
            Restart=always
            Environment=NODE_ENV=production

            [Install]
            WantedBy=multi-user.target
            EOF'
            
            # Reload services
            sudo systemctl daemon-reload
            
            # Enable and start service
            sudo systemctl enable hello-api
            sudo systemctl restart hello-api
            
            # Verify service status
            sudo systemctl status hello-api