name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      # Fix SSH host verification
      - name: Add VM to known hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          strict: false  # Disable strict host checking
          script: |
            # Create app directory
            sudo mkdir -p /opt/app
            sudo chown ${{ secrets.VM_USERNAME }}:${{ secrets.VM_USERNAME }} /opt/app
            
            # Copy code using SCP (more reliable)
            scp -r ./* ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/opt/app/
            
            # Set ownership
            sudo chown -R ${{ secrets.VM_USERNAME }}:${{ secrets.VM_USERNAME }} /opt/app
            
            # Install production dependencies
            cd /opt/app
            npm ci --omit=dev
            
            # Create systemd service
            sudo tee /etc/systemd/system/hello-api.service > /dev/null <<EOF
            [Unit]
            Description=Hello API Service
            After=network.target
            
            [Service]
            User=${{ secrets.VM_USERNAME }}
            WorkingDirectory=/opt/app
            ExecStart=/usr/bin/node index.js
            Restart=always
            RestartSec=5
            Environment=NODE_ENV=production
            Environment=PATH=/usr/bin:/usr/local/bin
            
            [Install]
            WantedBy=multi-user.target
            EOF
            
            # Reload and restart service
            sudo systemctl daemon-reload
            sudo systemctl enable hello-api
            sudo systemctl restart hello-api
            sleep 5
            sudo systemctl status hello-api
            # Verify process is running
            pgrep -f "node index.js" || (echo "Process not running!" && exit 1)